spring.application.name=chat
#spring.data.redis.host=${SPRING_REDIS_HOST}
#spring.data.redis.port=${SPRING_REDIS_PORT}
# Temporary check to see if Redis connects
spring.data.redis.host=localhost
spring.data.redis.port=6379